name: Deploy on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t yourusername/yourproject:pr-${{ github.event.number }} .
        docker push yourusername/yourproject:pr-${{ github.event.number }}

    - name: Deploy to server
      run: |
        ssh user@server "docker pull yourusername/yourproject:pr-${{ github.event.number }} && docker run -d -p 8000:8000 yourusername/yourproject:pr-${{ github.event.number }}"
